package: code
version: '1.0.0'
author: KLXM
supportpage: https://github.com/klxm/code

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'

# Sicherheitseinstellungen
config:
    # Automatische Deaktivierung nach X Tagen (0 = deaktiviert)
    auto_deactivate_after_days: 2
    # Daten vor Deaktivierung bereinigen (Backups, Trash)
    cleanup_data_on_deactivate: true

page:
    title: 'translate:code_title' 
    perm: admin[]
    icon: rex-icon fa-code
    subpages:
        main: 
            title: 'translate:code_browser'
        search:
            title: 'translate:code_search'
        backups:
            title: 'Backup & Trash'
